"""add_parent_task_id_to_parse_tasks

Revision ID: 361905fa1cd8
Revises: 9fa6fd732869
Create Date: 2025-06-25 01:28:44.325149

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '361905fa1cd8'
down_revision: Union[str, None] = '9fa6fd732869'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('parse_tasks', sa.Column('parent_task_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_parse_tasks_parent_task_id'), 'parse_tasks', ['parent_task_id'], unique=False)
    op.create_foreign_key(None, 'parse_tasks', 'parse_tasks', ['parent_task_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'parse_tasks', type_='foreignkey')
    op.drop_index(op.f('ix_parse_tasks_parent_task_id'), table_name='parse_tasks')
    op.drop_column('parse_tasks', 'parent_task_id')
    # ### end Alembic commands ###
