"""remove_directory_path_and_index_description_from_vector_store_tasks

Revision ID: 9b69ff268046
Revises: 494a5726f88d
Create Date: 2025-06-09 11:52:44.819447

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9b69ff268046'
down_revision: Union[str, None] = '494a5726f88d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Check if table and columns exist before dropping columns
    from sqlalchemy import inspect
    conn = op.get_bind()
    inspector = inspect(conn)
    if 'vector_store_tasks' in inspector.get_table_names():
        columns = [col['name'] for col in inspector.get_columns('vector_store_tasks')]
        if 'directory_path' in columns:
            op.drop_column('vector_store_tasks', 'directory_path')
        if 'index_description' in columns:
            op.drop_column('vector_store_tasks', 'index_description')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Check if table exists before adding columns
    from sqlalchemy import inspect
    conn = op.get_bind()
    inspector = inspect(conn)
    if 'vector_store_tasks' in inspector.get_table_names():
        op.add_column('vector_store_tasks', sa.Column('index_description', sa.TEXT(), autoincrement=False, nullable=True))
        op.add_column('vector_store_tasks', sa.Column('directory_path', sa.TEXT(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
