"""add soft_deleted_at to chat_sessions

Revision ID: 9f304976c801
Revises: b154b7df3eb1
Create Date: 2025-06-09 15:02:28.126413

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9f304976c801'
down_revision: Union[str, None] = 'b154b7df3eb1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_sessions', sa.Column('soft_deleted_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chat_sessions', 'soft_deleted_at')
    # ### end Alembic commands ###
