"""add_missing_fields_to_vector_store_tasks

Revision ID: b154b7df3eb1
Revises: 9b69ff268046
Create Date: 2025-06-09 12:18:18.451249

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = 'b154b7df3eb1'
down_revision: Union[str, None] = '9b69ff268046'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Add missing fields to vector_store_tasks table
    op.add_column('vector_store_tasks', sa.Column('processed_files', postgresql.JSON(astext_type=sa.Text()), nullable=True, default=list))
    op.add_column('vector_store_tasks', sa.Column('total_files', sa.Integer(), nullable=True, default=0))
    op.add_column('vector_store_tasks', sa.Column('total_documents', sa.Integer(), nullable=True, default=0))
    op.add_column('vector_store_tasks', sa.Column('total_nodes', sa.Integer(), nullable=True, default=0))
    op.add_column('vector_store_tasks', sa.Column('index_id', sa.String(255), nullable=True))
    op.add_column('vector_store_tasks', sa.Column('vector_store_path', sa.Text(), nullable=True))
    op.add_column('vector_store_tasks', sa.Column('config', postgresql.JSON(astext_type=sa.Text()), nullable=True, default=dict))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Remove the added fields from vector_store_tasks table
    op.drop_column('vector_store_tasks', 'config')
    op.drop_column('vector_store_tasks', 'vector_store_path')
    op.drop_column('vector_store_tasks', 'index_id')
    op.drop_column('vector_store_tasks', 'total_nodes')
    op.drop_column('vector_store_tasks', 'total_documents')
    op.drop_column('vector_store_tasks', 'total_files')
    op.drop_column('vector_store_tasks', 'processed_files')
    # ### end Alembic commands ###
