"""Initial migration for chat sessions and messages

Revision ID: f8e6fc69710d
Revises: 
Create Date: 2025-06-04 21:32:14.255785

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f8e6fc69710d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat_sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.String(length=255), nullable=False),
    sa.Column('index_ids', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_activity', sa.DateTime(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('session_metadata', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chat_sessions_session_id'), 'chat_sessions', ['session_id'], unique=True)
    op.create_table('chat_messages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('message_metadata', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['chat_sessions.session_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chat_messages_session_id'), 'chat_messages', ['session_id'], unique=False)
    op.drop_index('data_test_migration_index_embedding_idx', table_name='data_test_migration_index', postgresql_with={'m': '16', 'ef_construction': '64'}, postgresql_using='hnsw')
    op.drop_index('test_migration_index_idx_1', table_name='data_test_migration_index')
    op.drop_table('data_test_migration_index')
    op.drop_index('data_vector_store_test_index1_embedding_idx', table_name='data_vector_store_test_index1', postgresql_with={'m': '16', 'ef_construction': '64'}, postgresql_using='hnsw')
    op.drop_index('vector_store_test_index1_idx_1', table_name='data_vector_store_test_index1')
    op.drop_table('data_vector_store_test_index1')
    op.drop_index('data_vector_store_dd2fa02d_0f1a_43fe_b84d_f424e22902b4_embeddin', table_name='data_vector_store_dd2fa02d_0f1a_43fe_b84d_f424e22902b4', postgresql_with={'m': '16', 'ef_construction': '64'}, postgresql_using='hnsw')
    op.drop_index('vector_store_dd2fa02d_0f1a_43fe_b84d_f424e22902b4_idx_1', table_name='data_vector_store_dd2fa02d_0f1a_43fe_b84d_f424e22902b4')
    op.drop_table('data_vector_store_dd2fa02d_0f1a_43fe_b84d_f424e22902b4')
    op.drop_index('vector_store_7a8ebe69-99b6-41a8-8e4a-2a0eb54c4c48_idx_1', table_name='data_vector_store_7a8ebe69-99b6-41a8-8e4a-2a0eb54c4c48')
    op.drop_table('data_vector_store_7a8ebe69-99b6-41a8-8e4a-2a0eb54c4c48')
    op.drop_index('data_vector_store_test_migration_index_embedding_idx', table_name='data_vector_store_test_migration_index', postgresql_with={'m': '16', 'ef_construction': '64'}, postgresql_using='hnsw')
    op.drop_index('vector_store_test_migration_index_idx_1', table_name='data_vector_store_test_migration_index')
    op.drop_table('data_vector_store_test_migration_index')
    op.drop_index('data_vector_store_aa1030ad_c615_4d49_b359_340f0fb3afaf_embeddin', table_name='data_vector_store_aa1030ad_c615_4d49_b359_340f0fb3afaf', postgresql_with={'m': '16', 'ef_construction': '64'}, postgresql_using='hnsw')
    op.drop_index('vector_store_aa1030ad_c615_4d49_b359_340f0fb3afaf_idx_1', table_name='data_vector_store_aa1030ad_c615_4d49_b359_340f0fb3afaf')
    op.drop_table('data_vector_store_aa1030ad_c615_4d49_b359_340f0fb3afaf')
    op.drop_index('data_vector_store_771f3739_7448_488a_89d3_d18a99b16408_embeddin', table_name='data_vector_store_771f3739_7448_488a_89d3_d18a99b16408', postgresql_with={'m': '16', 'ef_construction': '64'}, postgresql_using='hnsw')
    op.drop_index('vector_store_771f3739_7448_488a_89d3_d18a99b16408_idx_1', table_name='data_vector_store_771f3739_7448_488a_89d3_d18a99b16408')
    op.drop_table('data_vector_store_771f3739_7448_488a_89d3_d18a99b16408')
    op.drop_index('data_vector_store_test_index2_embedding_idx', table_name='data_vector_store_test_index2', postgresql_with={'m': '16', 'ef_construction': '64'}, postgresql_using='hnsw')
    op.drop_index('vector_store_test_index2_idx_1', table_name='data_vector_store_test_index2')
    op.drop_table('data_vector_store_test_index2')
    op.drop_index('data_vector_store_1b70e012_79b7_4b20_8f70_9e94646e3aad_embeddin', table_name='data_vector_store_1b70e012_79b7_4b20_8f70_9e94646e3aad', postgresql_with={'m': '16', 'ef_construction': '64'}, postgresql_using='hnsw')
    op.drop_index('vector_store_1b70e012_79b7_4b20_8f70_9e94646e3aad_idx_1', table_name='data_vector_store_1b70e012_79b7_4b20_8f70_9e94646e3aad')
    op.drop_table('data_vector_store_1b70e012_79b7_4b20_8f70_9e94646e3aad')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('data_vector_store_1b70e012_79b7_4b20_8f70_9e94646e3aad',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('text', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('metadata_', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('node_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('embedding', sa.NullType(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='data_vector_store_1b70e012_79b7_4b20_8f70_9e94646e3aad_pkey')
    )
    op.create_index('vector_store_1b70e012_79b7_4b20_8f70_9e94646e3aad_idx_1', 'data_vector_store_1b70e012_79b7_4b20_8f70_9e94646e3aad', [sa.text("(metadata_ ->> 'ref_doc_id'::text)")], unique=False)
    op.create_index('data_vector_store_1b70e012_79b7_4b20_8f70_9e94646e3aad_embeddin', 'data_vector_store_1b70e012_79b7_4b20_8f70_9e94646e3aad', ['embedding'], unique=False, postgresql_with={'m': '16', 'ef_construction': '64'}, postgresql_using='hnsw')
    op.create_table('data_vector_store_test_index2',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('text', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('metadata_', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('node_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('embedding', sa.NullType(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='data_vector_store_test_index2_pkey')
    )
    op.create_index('vector_store_test_index2_idx_1', 'data_vector_store_test_index2', [sa.text("(metadata_ ->> 'ref_doc_id'::text)")], unique=False)
    op.create_index('data_vector_store_test_index2_embedding_idx', 'data_vector_store_test_index2', ['embedding'], unique=False, postgresql_with={'m': '16', 'ef_construction': '64'}, postgresql_using='hnsw')
    op.create_table('data_vector_store_771f3739_7448_488a_89d3_d18a99b16408',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('text', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('metadata_', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('node_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('embedding', sa.NullType(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='data_vector_store_771f3739_7448_488a_89d3_d18a99b16408_pkey')
    )
    op.create_index('vector_store_771f3739_7448_488a_89d3_d18a99b16408_idx_1', 'data_vector_store_771f3739_7448_488a_89d3_d18a99b16408', [sa.text("(metadata_ ->> 'ref_doc_id'::text)")], unique=False)
    op.create_index('data_vector_store_771f3739_7448_488a_89d3_d18a99b16408_embeddin', 'data_vector_store_771f3739_7448_488a_89d3_d18a99b16408', ['embedding'], unique=False, postgresql_with={'m': '16', 'ef_construction': '64'}, postgresql_using='hnsw')
    op.create_table('data_vector_store_aa1030ad_c615_4d49_b359_340f0fb3afaf',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('text', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('metadata_', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('node_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('embedding', sa.NullType(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='data_vector_store_aa1030ad_c615_4d49_b359_340f0fb3afaf_pkey')
    )
    op.create_index('vector_store_aa1030ad_c615_4d49_b359_340f0fb3afaf_idx_1', 'data_vector_store_aa1030ad_c615_4d49_b359_340f0fb3afaf', [sa.text("(metadata_ ->> 'ref_doc_id'::text)")], unique=False)
    op.create_index('data_vector_store_aa1030ad_c615_4d49_b359_340f0fb3afaf_embeddin', 'data_vector_store_aa1030ad_c615_4d49_b359_340f0fb3afaf', ['embedding'], unique=False, postgresql_with={'m': '16', 'ef_construction': '64'}, postgresql_using='hnsw')
    op.create_table('data_vector_store_test_migration_index',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('text', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('metadata_', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('node_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('embedding', sa.NullType(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='data_vector_store_test_migration_index_pkey')
    )
    op.create_index('vector_store_test_migration_index_idx_1', 'data_vector_store_test_migration_index', [sa.text("(metadata_ ->> 'ref_doc_id'::text)")], unique=False)
    op.create_index('data_vector_store_test_migration_index_embedding_idx', 'data_vector_store_test_migration_index', ['embedding'], unique=False, postgresql_with={'m': '16', 'ef_construction': '64'}, postgresql_using='hnsw')
    op.create_table('data_vector_store_7a8ebe69-99b6-41a8-8e4a-2a0eb54c4c48',
    sa.Column('id', sa.BIGINT(), server_default=sa.text('nextval(\'"data_vector_store_7a8ebe69-99b6-41a8-8e4a-2a0eb54c4c48_id_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('text', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('metadata_', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('node_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('embedding', sa.NullType(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='data_vector_store_7a8ebe69-99b6-41a8-8e4a-2a0eb54c4c48_pkey')
    )
    op.create_index('vector_store_7a8ebe69-99b6-41a8-8e4a-2a0eb54c4c48_idx_1', 'data_vector_store_7a8ebe69-99b6-41a8-8e4a-2a0eb54c4c48', [sa.text("(metadata_ ->> 'ref_doc_id'::text)")], unique=False)
    op.create_table('data_vector_store_dd2fa02d_0f1a_43fe_b84d_f424e22902b4',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('text', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('metadata_', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('node_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('embedding', sa.NullType(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='data_vector_store_dd2fa02d_0f1a_43fe_b84d_f424e22902b4_pkey')
    )
    op.create_index('vector_store_dd2fa02d_0f1a_43fe_b84d_f424e22902b4_idx_1', 'data_vector_store_dd2fa02d_0f1a_43fe_b84d_f424e22902b4', [sa.text("(metadata_ ->> 'ref_doc_id'::text)")], unique=False)
    op.create_index('data_vector_store_dd2fa02d_0f1a_43fe_b84d_f424e22902b4_embeddin', 'data_vector_store_dd2fa02d_0f1a_43fe_b84d_f424e22902b4', ['embedding'], unique=False, postgresql_with={'m': '16', 'ef_construction': '64'}, postgresql_using='hnsw')
    op.create_table('data_vector_store_test_index1',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('text', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('metadata_', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('node_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('embedding', sa.NullType(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='data_vector_store_test_index1_pkey')
    )
    op.create_index('vector_store_test_index1_idx_1', 'data_vector_store_test_index1', [sa.text("(metadata_ ->> 'ref_doc_id'::text)")], unique=False)
    op.create_index('data_vector_store_test_index1_embedding_idx', 'data_vector_store_test_index1', ['embedding'], unique=False, postgresql_with={'m': '16', 'ef_construction': '64'}, postgresql_using='hnsw')
    op.create_table('data_test_migration_index',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('text', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('metadata_', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('node_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('embedding', sa.NullType(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='data_test_migration_index_pkey')
    )
    op.create_index('test_migration_index_idx_1', 'data_test_migration_index', [sa.text("(metadata_ ->> 'ref_doc_id'::text)")], unique=False)
    op.create_index('data_test_migration_index_embedding_idx', 'data_test_migration_index', ['embedding'], unique=False, postgresql_with={'m': '16', 'ef_construction': '64'}, postgresql_using='hnsw')
    op.drop_index(op.f('ix_chat_messages_session_id'), table_name='chat_messages')
    op.drop_table('chat_messages')
    op.drop_index(op.f('ix_chat_sessions_session_id'), table_name='chat_sessions')
    op.drop_table('chat_sessions')
    # ### end Alembic commands ###
